before:
  hooks:
    - go mod tidy

builds:
  - id: issgo
    main: .
    binary: issgo
    ldflags:
      - -s -w
      - -X github.com/issgo/issgo/cmd.Version={{.Version}}
      - -X github.com/issgo/issgo/cmd.BuildTime={{.Date}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - README-en.md
      - LICENSE

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"

release:
  draft: false
  prerelease: auto
